const CAMPAIGN_STATUS = {
  DRAFT: 'DRAFT',
  WAITING: 'WAITING',
  RUNNING: 'RUNNING',
  PAUSE: 'PAUSE',
  END: 'END',
};

const CAMPAIGN_VISIBILITY = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
};

const SSO_EVENT = {
  CREATE_USER: 'CREATE_USER',
  SET_TOKEN: 'SET_TOKEN',
  LOGOUT: 'LOGOUT',
};

const CAMPAIGN_USER_ROLE = {
  USER: 'user',
  ADMIN: 'admin',
};

module.exports = {
  A_WEEK: 7 * 86400 * 1000,
  CAMPAIGN_STATUS,
  CAMPAIGN_VISIBILITY,
  SSO_EVENT,
  CAMPAIGN_USER_ROLE,
};
