const CAMPAIGN_STATUS = {
  WAITING: 'WAITING',
  RUNNING: 'RUNNING',
  PAUSE: 'PAUSE',
  END: 'END',
};

const PARTICIPATION_STATUS = {
  INVITED: 'INVITED',
  JOINED: 'JOINED',
};

const CAMPAIGN_VISIBILITY = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
};

const COLLECT_DATA_SYSTEM = {
  FAQ: 'FAQ',
  SLU: 'SLU',
  ASR: 'ASR',
  CHB: 'CHB',
  CHH: 'CHH',
};

const EVENT_JOIN_CAMPAIGN = {
  JOIN: 'JOIN',
  ACCEPT_INVITE: 'ACCEPT_INVITE',
};

const SSO_EVENT = {
  CREATE_USER: 'CREATE_USER',
  SET_TOKEN: 'SET_TOKEN',
  LOGOUT: 'LOGOUT',
};

module.exports = {
  A_WEEK: 7 * 86400 * 1000,
  CAMPAIGN_STATUS,
  PARTICIPATION_STATUS,
  CAMPAIGN_VISIBILITY,
  COLLECT_DATA_SYSTEM,
  EVENT_JOIN_CAMPAIGN,
  SSO_EVENT,
};
